# Generated by Django 2.2.3 on 2024-03-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20240313_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
